persona:
    resource: "@PersonaBundle/Resources/config/routing.yml"
    prefix:   /

hospitalizacion:
    resource: "@HospitalizacionBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation
    